version: "3.8"

services:
  dev:
    container_name: red-tetris
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "5173:5173"
    command: sh -c "set +x && npm install && npm run build && npm run serv & npx vite --host"
